#Whether to use this config to change the number of curio slots.
#When changing the number using datapack etc. with modpack etc., please set this config to false.
enableCurioSlotModification = false
#Increases or decreases the number of curio slots by the specified amount.
#This does not set the actual number of slots, but rather represents a relative change.
#The actual number of slots will be the default number of slots plus (or minus) the amount specified in this config.
#Since the number of slots can be changed by other mods or datapacks, the actual number of slots may not always follow this rule.
# Default: 0
# Range: > -2147483648
curioSlotModification = 0
