#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 27 13:44:58 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Solas Shader V3.7.zip
