#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 04 02:57:40 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=Solas Shader V3.7.zip
