version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
everycomp = true
create_new_age = true
farmersdelight = true
morepropulsion = true
createpolymer = true
gnkinetics = true
someassemblyrequired = true
extra_gauges = true
any_lanterns = true
appliedtacz = true
aether_beyond_parity = true
createsprings = true
alexscaves = true
cbcmoreshells = true
frictionless_ceramic = true
copycats = true
domum_ornamentum = true
cnbridge = true
aether = true
oilcanister = true
sealife = true
permanentsponges = true
ftbquests = true
create_winery = true
fluid = true
divinefarmland = true
drill_drain = true
createbigcannons = true
dyenamics = true
create_confectionery = true
createprism = true
ldlib2 = true
createthrusters = true
deeperdarker = true
petrolpark = true
doggytalents = true
create = true
create_aeronautics_toolgun = true
minecolonies = true
create_ironworks = true
aerocali = true
visualworkbench = true
createmetalwork = true
createoreexcavation = true
multipiston = true
create_jetpack = true
greenhousegardener = true
dragonlib = true
sliceanddice = true
waystones = true
create_more_additions = true
protection_pixel = true
create_flight_control = true
tracks = true
born_in_chaos_v1 = true
bigtires = true
create_power_loader = true
createsolar = true
taczarmor = true
createqol = true
create_sponges = true
alexsmobs = true
cbc_autotarget = true
neovitae = true
createpropulsion = true
create_iron_vaults = true
createstockbridge = true
create_optical = true
easymagic = true
quark = true
ballastmod = true
occultism_dyenamics = true
dndecor = true
bmaddon = true
boatpropellerbearing = true
createmechanicalconfection = true
create_sa = true
hotstuff = true
create_diamond_factory = true
mechanicalmillstone = true
createteleporters = true
create_hypertube = true
volcanicmason = true
pantographsandwires = true
create_overdrive = true
aeronautics = true
simulated = true
interiors = true
createnetherindustry = true
direct_chute = true
create_dragons_plus = true
synaxis = true
ars_additions = true
ae2 = true
northstar = true
ars_nouveau = true
chemica = true
cbbees = true
creategarnished = true
serene_shrubbery = true
pipeorgans = true
create_integrated_farming = true
gyro = true
kaleidoscope_cookery = true
totemfactory = true
createtransmission = true
createcolonies = true
createcafe = true
simulatedcoasters = true
create_lnl = true
arseng = true
create_wrapped = true
easyanvils = true
aether_enhanced_extinguishing = true
create_submarine = true
appliedcreate = true
colored_packages = true
create_aeronautics_automated_logistics = true
create_chimneys = true
touhou_little_maid = true
ars_technica = true
arcanelanterns = true
railways = true
create_rns = true
bits_n_bobs = true
aether_treasure_reforging = true
handcrafted = true
create_auto_track = true
rechiseledcreate = true
create_radar = true
ddcl = true
ars_creo = true
create_complex_recipes = true
ars_controle = true
dndesires = true
offroad = true
create_vibrant_vaults = true
pretty_in_pink = true
kaleidoscope_end = true
supplementaries = true
ars_monde_lib = true
create_fantasizing = true
createminecolonies = true
kaleidoscope_nether = true
create_deep_dark = true
aerowarptics = true
minecraft = true
occultism = true
azimuth = true
mowziesmobs = true
create_connected = true
create_mob_spawners = true
trading_floor = true
createaddition = true
powergrid = true
sable_schematic_api = true
enderstorage = true
airstarter = true
aerocables = true
createframed = true
tradingpost = true
create_bb = true
create_creative = true
petrolsparts = true
create_compat_core = true
createnuclear = true
create_aquatic_ambitions = true
illagerinvasion = true
swem = true
aeroworks = true
blocksyouneed_luna = true
streamsreflowing = true
createfood = true
sable_pallets = true
createtimemanipulator = true
create_aeronautics_throwable_rope_connector = true
s_a_b = true
endersourcejars = true
cataclysm = true
mechanical_botany = true
createmoregirder = true
aether_overworld_ores = true
createendergateway = true
create_enchantment_industry = true
citadel = true
createdieselgenerators = true
create_furnitures = true
northstar_structures = true
extra_copycats = true
aeronautics_utility_objects = true
createfillthecolonies = true
escalated = true
fastpaintings = true
bellsandwhistles = true
cbc_at = true
amendments = true
create_aero_radar = true
tacz = true
diagonalfences = true
moonlight = true
createpureglass = true
blazinghot = true
electroenergetics = true
create_tweaked_controllers = true
torchmaster = true
sable_kardanwelle = true
create_train_parts = true
casualswing = true
backpacked = true
theurgy = true
create_factory = true
picaxe = true
tfmg = true
sawmill = true
chipped = true
create_delete_and_repeat = true
vista = true
aeronautics_dyeable_components = true
mctradepost = true
createcasing = true
createmissiles = true
vsfluidlink = true
structurize = true
i_architecture = true
create_blaze_burner_fuels = true
struts = true
createdeco = true
create_simple_generator = true
create_better_motors = true
create_things_and_misc = true
touys = true
ars_elemental = true
create_mobile_packages = true
linearbearing = true
reddensstonelantern = true
forbidden_arcanus = true
create_chocolate_fountain = true
sauce = true
enchantinginfuser = true
create_alternativehoneyreborn = true
rechiseled = true
