["Module Opener #模块特性开关#"]
	#Open the module to use the remastered eating AI system (default: true)
	# 开启此模块将会启用重制的市民进食AI (默认开启)
	enableNewEatingModule = true
	#Open the module to use the remastered flee AI system (default: true)
	# 开启此模块将会启用重制的市民逃跑AI (默认开启)
	enableNewFleeModule = true
	#Open the module to use the remastered smeltery AI system for chef and stone smeltery(default: true)
	# 开启此模块将会启用重制的厨师和冶炼工人AI (默认开启)
	enableNewSmelteryModule = true
	#Open the module to use the remastered farmer AI system (default: true)
	# 开启此模块将会启用重制的农夫AI (默认开启)
	enableNewFarmerModule = true
	#Open the module to use the remastered deliveryman AI system (default: true)
	# 开启此模块将会启用重制的快递员AI (默认开启)
	enableNewDeliverymanModule = true

["Building Module Opener #房屋模块特性开关#"]
	#Open this to assign visitors directly trough tavern block (default: true)
	# 开启这个可以直接在酒馆雇佣游客(默认开启)
	enableTavernAssignmentModule = true
	#Open this to add minimum stock module to most of huts (default: true)
	# 开启这个可以直接在酒馆雇佣游客 (默认开启)
	additionalMinimumStockModule = true
	#Open this to add food black list to specific huts, you can edit exactly what workers won't eat at those huts(default: true)
	# 开启这个可以给某几个特定的小屋增加员工禁食清单，这样员工就不会取食你所选定的食物 (默认开启)
	foodBlackListModule = true

["Easycolony Feature #简易殖民地相关特性开关#"]
	#Is citizen alert when get hurt? (default: true)
	# 市民是否警告玩家自己受伤？(默认开启)
	messageDisplay = true

	["Easycolony Feature #简易殖民地相关特性开关#"."Resurrect #复活配置"]
		#是否允许玩家手动复活市民：如果允许，玩家将可以使用指定物品复活市民，成功率取决于总幸福度和墓地等级。
		allow_resurrect = true
		#复活市民所需物品：指定玩家复活市民所需的物品。
		resurrect_item = "minecraft:totem_of_undying"
		#复活市民几率乘数：会在原有的复活概率基础上额外乘以一个系数。
		# Default: 1.0
		# Range: 0.0 ~ 2.147483647E9
		resurrect_chance_multiplier = 1.0

	["Easycolony Feature #简易殖民地相关特性开关#"."Mind Reader #市民思维读取器设置"]
		#是否允许玩家读取市民行动：如果允许，玩家将可以手持特定物品右键市民读取市民当前行动。
		allow_read_mind = true
		#读取行动所需物品：指定玩家读取市民行动所需的物品，不会消耗。
		read_mind_item = "minecraft:compass"

["Update Message Display #更新信息显示#"]
	#Is changelogs display in-game when new version updated? (default: true)
	# 是否在游戏内部显示最新版本更新信息？(默认开启)
	messageDisplay = false

	["Pathing Cost Modifier #寻路Cost相关设置#"."Multiplier #乘子系数#"]
		#Rail path cost multiplier (default: 0.1, original:0.1) #铁轨Cost乘数 (默认 : 0.1 殖民地原设置 : 0.1)#
		# Default: 0.1
		# Range: 0.0 ~ 2.0
		railCostMultiplier = 0.1
		#Road path cost multiplier (default: 0.25, original:1/6) #路径Cost乘数 (默认 : 0.4 殖民地原设置 : 1/6)#
		# Default: 0.25
		# Range: 0.0 ~ 2.0
		roadCostMultiplier = 0.25
		#Drop cost multiplier (default: 1.0, original:1.0)
		##掉落Cost乘数 (默认 : 1.0 殖民地原设置 : 1.0)#
		#Notice: The base formula for falling cost has been modified from |dY|³ to |dY| ^ 4.
		##注意:下落Cost基础公式已经从 |dY|³ 修改为 |dY| ^ 4 #
		# Default: 1.0
		# Range: 0.0 ~ 10.0
		dropCostMultiplier = 1.0

	["Pathing Cost Modifier #寻路Cost相关设置#"."Basic Cost Definer #基础Cost定义#"]
		#Water path cost addon (default: 12.0, original:2.0) #水路Cost (默认 : 12.0 殖民地原设置 : 2.0)#
		# Default: 12.0
		# Range: 0.0 ~ 63.0
		waterCostAddon = 12.0
		#Jump cost addon (default: 4.0, original:2.0) #跳跃(准确来说是非梯子爬升)Cost (默认 : 4.0 殖民地原设置 : 2.0)#
		# Default: 4.0
		# Range: 0.0 ~ 63.0
		jumpCostAddon = 4.0
		#In shape cost addon (default: 2.0, original:2.0) #实体方块内部行走的Cost (默认 : 2.0 殖民地原设置 : 2.0)#
		# Default: 2.0
		# Range: 0.0 ~ 63.0
		inShapeCostAddon = 2.0
		#Door and trapdoor’s cost addon (default: 3.0, original:3.0) #穿过各种"门"的Cost (默认 : 3.0 殖民地原设置 : 3.0)#
		# Default: 3.0
		# Range: 0.0 ~ 63.0
		doorsCostAddon = 3.0
		#Dive cost addon (default: 48.0, original:4.0) #潜水(潜多了会淹死)的Cost (默认 : 48.0 殖民地原设置 : 4.0)#
		# Default: 48.0
		# Range: 0.0 ~ 63.0
		diveCostAddon = 48.0
		#Breathing cave air cost addon (default: 0.3, original:3.0) #钻洞(人工的也算)的Cost,(默认 : 0.3 殖民地原设置 : 3.0)#
		# Default: 0.3
		# Range: 0.0 ~ 63.0
		caveCostAddon = 0.3
		#Exit railway cost addon (default: 4.0, original:4.0) #下铁路(人工的也算)的Cost(探测铁轨为”站点“，不计cost) (默认 : 4.0 殖民地原设置 : 4.0)#
		# Default: 4.0
		# Range: 0.0 ~ 63.0
		railExitAddon = 4.0

	["Pathing Cost Modifier #寻路Cost相关设置#"."Typical Cost Definer #针对性Cost定义#"]
		#Cost on switch ladder when climbing (default: 18.0) #攀爬时切换梯子的Cost (默认 : 18.0)#
		# Default: 18.0
		# Range: 0.0 ~ 63.0
		ladderSwitchCostAddon = 18.0
		#Walk on shingle cost addon (default: 6.0, original:3.0) #上房揭瓦(走在屋瓦上)的Cost (默认 : 6.0 殖民地原设置 : 3.0)#
		# Default: 6.0
		# Range: 0.0 ~ 63.0
		shingleCostAddon = 6.0
		#Jump in farmland or drop onto farmland cost addon (default: 24.0) #在农田中跳上跳下的Cost (默认 : 24.0)#
		# Default: 24.0
		# Range: 0.0 ~ 63.0
		farmlandCostAddon = 24.0
		#Walk on leaves cost addon (default: 8.0) #爬树(走在树叶上)的Cost (默认 : 8.0)#
		# Default: 8.0
		# Range: 0.0 ~ 63.0
		leafCostAddon = 8.0
		#Walk in sweet berry bush cost addon (default: 63.0) #被浆果丛扎的Cost (默认 : 63.0)#
		# Default: 63.0
		# Range: 0.0 ~ 63.0
		berryCostAddon = 63.0

	["Pathing Cost Modifier #寻路Cost相关设置#"."Advanced Pathfinding Constant Definer #进阶寻路算法常数定义(警告：慎重修改！会对全局寻路产生极大影响！)#"]
		#When traversing callback nodes, there is a heuristic reduction on artificial roads. This value is used to control the rate at which the heuristic for railway callback nodes increases, and its formula is: RAIL_COST_MULTIPLIER * ONRAIL_CALLBACK_MULTIPLIER (default: 1.0) 
		#走回头路(其节点暂定义为回扣节点)时在人工道路上会有启发值减免,这是用来控制铁路回扣节点启发值增加速度的数值，其算式为 RAIL_COST_MULTIPLIER * ONRAIL_CALLBACK_MULTIPLIER (默认 : 1.0)
		# Default: 1.0
		# Range: 0.0 ~ 2.0
		onRailCallbackMutiplier = 1.0
		#This value is used to control the rate at which the heuristic for callback nodes on road blocks increases, and its formula is: ROAD_COST_MULTIPLIER * ONROAD_CALLBACK_MULTIPLIER (default: 1.2) 
		#用来控制道路方块上回扣节点启发值增加速度的数值，其算式为 ROAD_COST_MULTIPLIER * ONROAD_CALLBACK_MULTIPLIER (默认 : 1.2)
		# Default: 1.2
		# Range: 0.0 ~ 2.0
		onRoadCallbackMutiplier = 1.2
		#This is a global heuristic reduction, representing how much villagers prefer railways when pathfinding far away from the target point. The smaller the value, the stronger the preference. (default: 0.5)
		#是一个全局的启发值减免，表现为村民在远离目标点处寻路时对铁路的信任程度，数值越小越信任(默认 : 0.5)
		# Default: 0.5
		# Range: 0.1 ~ 3.0
		onRailPreference = 0.5
		#This is a global heuristic reduction, representing how much villagers prefer path blocks when pathfinding far away from the target point. The smaller the value, the stronger the preference. (default: 0.78)
		#是一个全局的启发值减免，表现为村民在远离目标点处寻路时对道路方块的信任程度，数值越小越信任(默认 : 0.78)
		# Default: 0.78
		# Range: 0.4 ~ 3.0
		onRoadPreference = 0.78
		#This is a global heuristic multiplier, representing how much villagers prefer swimming when pathfinding far away from the target point. The smaller the value, the stronger the preference. (default: 1.3)
		#是一个全局的启发值乘子，表现为村民在远离目标点处寻路时对水路的信任程度，数值越小越信任(默认 : 1.6)
		# Default: 1.6
		# Range: 1.0 ~ 8.0
		swimmingPreference = 1.6
		#Tolerates how many times callback nodes can be expanded during each pathfinding process. (default: 2)
		# 能容忍每次寻路中回扣节点被扩展几次，数值过大可能会造成扩展的无用节点增加 (默认 : 2)
		# Default: 2
		# Range: 1 ~ 25
		callbackTimesTolerance = 2
		#Explore the "cheapest" X nodes at every step. (default: 4)
		# 每一步寻路时探索最优的 X 个节点 (默认 : 4)
		# Default: 4
		# Range: 1 ~ 25
		nodeExtendCount = 4

["Restaurant Related Modifier #餐厅相关逻辑修改#"]
	#Duration citizens wait in the restaurant for cook service (minutes) (default: 0.5, original: 2.0)
	#你的村民在餐厅等待厨师服务的时间(分钟) (默认 : 0.5 殖民地原设置 : 2.0)
	# Default: 0.5
	# Range: 0.0 ~ 2.0
	restaurantWaitingTime = 0.5

["Hospital Related Modifier #医院相关逻辑修改#"]
	#The percentage of HP at which your citizens will seek treatment. (default: 0.2, original: 0.0)
	#你的村民将在剩多少比例的HP时去寻求医生治疗 (默认 : 0.2 殖民地原设置 : 0.0)
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	curePercentageHP = 0.2
	#The absolute amount of HP at which your citizens will seek treatment. (default: 10.0, original: 6.0)
	#你的村民将在剩多少HP时去寻求医生治疗 (默认 : 10.0 殖民地原设置 : 6.0)
	# Default: 10.0
	# Range: 6.0 ~ 40.0
	cureHP = 10.0
	#Citizen will start to heal themselves at that time.
	# 市民开始自愈的时间(s)
	# Default: 480
	# Range: 0 ~ 4095
	startHeal = 480
	#Citizen will randomly cure during this time.
	# 市民将在这个时间段内均匀自愈(s)
	# Default: 2000
	# Range: 0 ~ 65535
	healDuration = 2000

["LumberJack Modifier #伐木工相关修改#"]
	#Lumberjcak will start to work only if hut is placed.
	# 伐木工会在放置工作方块后立即开始工作 (功能在后期有些超模，建议仅在前期开启以分担少量工作量)。
	lumberjackWorkWhenUnconstructed = false
	#Lumberjcak will replant without saplings, still consume saplings when have.
	# 伐木工在树苗不足时也会正常补种，但是有树苗时依旧会消耗树苗。
	lumberjackPlantWithoutSaplings = false
	#A toggle for lumberjacks to collect dropped items on trees in a more realistic but less efficient way (break leaves).
	#When disabled, uncollected items will instead be teleported directly to the lumberjack’s feet.
	#让伐木工收集树上的掉落物看起来更合理一些(破坏树叶)，效率相对比较低下，关闭后捡不到的物品会直接传送到伐木工脚下
	lumberjackBreakLeavesToGather = false
	#Time lumberjacks spend gathering a single item. Not recommended to set too long.
	#伐木工等待收集的时间，不过因为目前检测问题不建议时间过长
	# Default: 5
	# Range: 2 ~ 10
	lumberjackGatherWaitingTime = 5

["Builder Mode Modifier #土木人修改#"]
	#Builder mode (default: GIBBON), optional below: 建筑工人模式, (默认: 长臂猿)，可选项如下：
	#NORMAL: Normal mode, authentic. 常规: 默认选项，原汁原味的殖民地体验。
	#FORMALIST: Play as a formalist, jumping up and down on the construction site, but work when they just leave their hut. 形式主义者：像个形式主义者一样在工地上蹿下跳，但是会在离开土木小屋后立即开始工作。
	#SENTRY: Play as a sentry, stand at a stable position to build. 哨兵：像一个哨兵一样，站在工地的固定位置工作。
	#GOD: GOD SHOULD BUILD ANYWHERE THEY WANT. 创世神：神就应该想在哪儿干就在那儿干。
	#GIBBON: Play as a gibbon, jumping up and down with a large building range. 长臂猿：像猿猴一样上蹿下跳，但是只在一定建造范围内工作。
	#Allowed Values: NORMAL, FORMALIST, SENTRY, GOD, GIBBON
	builderMode = "GIBBON"
	#Miner mode (default: GIBBON), available modes are same as builder
	#矿工工作模式, (默认: 长臂猿)，可选模式与建筑工相同
	#Allowed Values: NORMAL, FORMALIST, SENTRY, GOD, GIBBON
	minerMode = "GIBBON"
	#Quarrier mode (default: GIBBON), available modes are same as builder
	#采石工工作模式, (默认: 长臂猿)，可选模式与建筑工相同
	#Allowed Values: NORMAL, FORMALIST, SENTRY, GOD, GIBBON
	quarrierMode = "GIBBON"
	#Building range of gibbon mode. 长臂猿模式下的建造范围。
	# Default: 20
	# Range: 0 ~ 128
	builderGibbonRange = 20
	#Can builder take orders everywhere. 打灰人能否随时随地接单。
	builderTakeOrdersEverywhere = true

["Herder Modifier #养殖户修改#"]
	#Max animal modifier, would you like to modify the max animals to 2^(building level)? (default: false)
	# 养殖场最大生物数是否改为 2^建筑等级 原为 2*建筑等级(动物数目过大会导致卡顿，所以不默认开启),(默认 : false)
	increaceMaxAnimal = false
	#Will butcher kill animals instantly? (default: true)
	# 屠户是否会秒杀动物 (默认 : true)
	butcherInstantKill = true

["Common Citizens Modifier #通用市民修改#"]
	#Open this to enable delivery man eat at warehouse.
	# 开启后快递员将会在仓库吃饭
	deliveryEatAtWareHouse = true
	#Crafters will use its max stock to craft as default, no need research to unlock.
	# 开启后工人会使用库存中余量最多的物品合成，无需点亮对应科技。
	crafterUseMaxStockFirst = true
	#Minimum stock can now be set in item counts rather than in stacks.
	# 开启后，最低存量将按个计数，而不是按组。
	minimumStockPrecise = false
	#Should citizens pick material at their own hut.
	# 你的非快递员市民是否应当在他们的小屋方块处取货。
	pickMaterialAtHut = true
	#Allows workers to use enchanted tools at their current level.
	# 允许工人在工具允许等级时就启用一部分低级附魔工具。
	earlyEnchant = true
	#Controls how many enchantment levels require 1 worker's hut level upgrade.
	# 每升一级可以允许额外附魔等级几级。
	# Default: 2
	# Range: 1 ~ 6
	enchantLevelScale = 2
	#Sets the maximum addtional worker's hut level enchantment tools.
	# 设置附魔工具最多需求小屋增加几级可用。
	# Default: 2
	# Range: 1 ~ 5
	maxAdditionalLevelForEnchantTools = 2
	#Punishment of normal food nutrition for citizens (It's a multiplier) (default: 1, original:0.25)
	#普通食物惩罚乘数 (默认 : 1， 殖民地原设置 : 0.25)
	# Default: 1.0
	# Range: 0.0 ~ 1.0
	foodPunisher = 1.0
	#Bonus of normal food nutrition for citizens (It's a multiplier on saturation) (default: 0.2)
	#普通食物奖励乘数(取决于食物饱和) (默认 : 0.2)
	# Default: 0.2
	# Range: 0.0 ~ 1.0
	normalFoodBonus = 0.2
	#Bonus of minecolonies' food nutrition for citizens (It's a multiplier on saturation) (default: 0.5)
	#殖民地食物奖励乘数(取决于食物饱和) (默认 : 0.5)
	# Default: 0.5
	# Range: 0.0 ~ 1.0
	minecoloniesFoodBonus = 0.5
	#Write In “Foods" that you don‘t want citizen to eat at colonies.
	#写入你不想市民在殖民地中吃的所有食物。
	generalFoodBlackList = []
	#Basic leisure time of citizens (s) (default: 180)
	#市民每次休息的默认时长(秒) (默认 : 0.5)
	# Default: 180
	# Range: 0 ~ 10000
	leisureTime = 180
	#Ratio of start a leisure per second. (Number as the x of 1/x) (default: 3600)
	#市民每秒有多少分之一的概率开始休息 (默认 : 0.5)
	# Default: 3600
	# Range: 1000 ~ 1000000
	leisureRatio = 3600
	#Defines how long would citizen decrease leisure time if their work are pretty “at leisure”, this will multiplied by their homebuilding level. (s) (default: 18)
	#这个时间会在村民空闲时累计，后面抵消它的休闲时间，此处用以控制抵消最大值，此值在实际应用时会乘以其住宅等级 (默认 : 18)
	# Default: 18
	# Range: 0 ~ 10000
	maxPreLeisureTime = 18
	#Open this to enable citizens to get beacon effect. (default: true)
	#开启这个可以让市民获得信标效果 (默认 : 开启)
	beaconEffect = true
	#Open this to disable citizens to teleport to their target when completely stuck. (default: false)
	#开启这个可以禁止市民寻路卡住时直接传送到目标地点 (默认 : 关闭)
	cancelTeleport = false

["Basic Logic Modifier #基础逻辑修改#"]
	#Max pathing distance (default: 1000, original:500)
	# 民最大寻路距离,(默认 : 1000 殖民地原设置 : 500)
	# Default: 1000
	# Range: 500 ~ 4095
	pathingDistance = 1000
	#Should player levite after doing things not allowed in your colony (default : false), 玩家是否会在你殖民地中做不允许的动作后被赋予漂浮buff (default : false)
	cancelLevitation = false
