[moon]
	#Enable moon crater generation
	enableCraters = true
	#Enable normal and old small/medium crater generation
	enableSmallMediumCraters = true
	#Enable normal and old large crater generation
	enableLargeCraters = true
	#Enable huge crater generation
	enableHugeCraters = true
	#Enable normal small crater generation
	enableSmallCrater = true
	#Enable normal medium crater generation
	enableMediumCrater = true
	#Enable normal large crater generation
	enableLargeCrater = true
	#Enable normal huge crater generation
	enableHugeCrater = true
	#Enable old small crater generation
	enableOldSmallCrater = true
	#Enable old medium crater generation
	enableOldMediumCrater = true
	#Enable old large crater generation
	enableOldLargeCrater = true
	#Enable old huge crater generation
	enableOldHugeCrater = true
	#Enable South Pole-Aitken basin generation
	enableSouthPoleAitkenBasin = false
