# Don't change this! Version used to track needed updates.
version = 1
disableParticles = false
byTypeReductions = {  }
maxParticlesPerSheet = 16384
particleRenderDistanceMultiplier = 0.6647058823529411
asynchronousTicking = true
reduceAllChance = 0.0
reduceDecreasedChance = 0.0
turnOffPotionParticlesV2 = [
    "NONE"
]